### PR TITLE
cf app-placement: WARN: Unresolved specs during Gem::Specification.reset

### PR DESCRIPTION
**Pull request by drnic**
```
~  gem install tools-cf-plugin
Fetching: tools-cf-plugin-3.0.0.gem (100%)
Successfully installed tools-cf-plugin-3.0.0
Installing ri documentation for tools-cf-plugin-3.0.0
1 gem installed
➜  ~  cf app-placement
WARN: Unresolved specs during Gem::Specification.reset:
      atomic (>= 0)
      net-ssh (>= 0)
      daemons (>= 1.1.5)
      thin (>= 1.4.1)
WARN: Clearing out unresolved specs.
```

### CODE REVIEW

**Comment by drnic** [comment]
When I create a new gemset:

```
$ gem install cf
$ gem install tools-cf-plugin
$ cf app-placement
/Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- net/ssh/gateway (LoadError)
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448@cf-tools/gems/tools-cf-plugin-3.0.0/lib/tools-cf-plugin/tunnel/base.rb:2:in `<top (required)>'
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448@cf-tools/gems/tools-cf-plugin-3.0.0/lib/tools-cf-plugin/tunnel/tunnel-nats.rb:6:in `<top (required)>'
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448@cf-tools/gems/tools-cf-plugin-3.0.0/lib/tools-cf-plugin/plugin.rb:6:in `<top (required)>'
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:142:in `require'
    from /Users/drnic/.rvm/gems/ruby-1.9.3-p448@cf-tools/gems/cf-5.4.0/lib/cf/plugin.rb:45:in `block in load_all'
```

**Comment by drnic** [comment]
```
$ gem install net-ssh-gateway
Fetching: net-ssh-gateway-1.2.0.gem (100%)
Successfully installed net-ssh-gateway-1.2.0
Installing ri documentation for net-ssh-gateway-1.2.0
1 gem installed
$  cf app-placement
works/fails as expected
```

**Comment by drnic** [comment]
Attached PR should fix latter issue. Not sure what caused initial issue.

**Comment by d** [comment]
Hi Nic,
  A couple issues:
- our CI is failing on this PR
- Have you tried applying this patch and running? (install gem in an empty gemset) We don't seem to be able to reproduce your success
  We have a theory that this is caused by `bosh_cli` not being included in the gemspec. If you have trouble after applying this patch, can you try that too?

@d and @sbrady 
Team Cloud Foundry

**Comment by jfoley** [comment]
Since this looks pretty stale, we are going to close it.

CF Community Pair (@chou & @jfoley)

**Pull request closed without merging**
